name: superheroes
description: project with using stream, bloc, rxdart, provider. data from  api


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  rxdart: ^0.27.7
  provider: ^6.0.5
  google_fonts: ^3.0.1
  cached_network_image: ^3.2.3
  http: ^0.13.5
  flutter_dotenv: ^5.0.2
  json_annotation: ^4.7.0
  shared_preferences: ^2.0.15



dev_dependencies:
  flutter_test:
    sdk: flutter
  network_image_mock: ^2.1.1
  build_runner: ^2.3.3
  json_serializable: ^6.5.4
  mockito: ^5.3.2




# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/google_fonts/
    - assets/images/
    - .env


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
